export const PAGES = {
  COMPLETE_PURCHASE: 'COMPLETE_PURCHASE',
  CONFIRM_PURCHASE: 'CONFIRM_PURCHASE',
  FEED: 'FEED',
  FEED_RECENTLY_ADDED: 'FEED_RECENTLY_ADDED',
  FEED_STAFF_PICKS: 'FEED_STAFF_PICKS',
  FEED_TRENDING: 'FEED_TRENDING',
  GALLERY: 'GALLERY',
  ACCOUNT: 'ACCOUNT',
  ARTISTS: 'ARTISTS',
  LEGACY_ASSET: 'LEGACY_ASSET',
  EDITION_TOKEN_OVERVIEW: 'EDITION_TOKEN_OVERVIEW',
  ACTIVITY: 'ACTIVITY',
};
